### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by deathcrow999** [deathcrow999/KillBlock#4]
Upon walking on emerald block nothing happens

**Comment by legoboy0215** [comment]
Sometimes it wont work... IDK why too. But I think code has problems?

**Comment by deathcrow999** [comment]
Ive been wracking my brain everything looks right to me ive recoded this several times before publishing anything on github and nothing seems to work

**Comment by legoboy0215** [comment]
I pushed a pull. Merge it.

**Comment by legoboy0215** [comment]
Ok?
